name: netallocation
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - coincbc
  - pip:
    - netallocation
  # - xarray
  # - progressbar2
  # - pypsa
  # - sparse
  # - dask
  # - pathlib
  # - h5py
  # - scipy
  # - pyyaml
  # - geopandas
  # - pandas
  # - cartopy